# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task3.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Task3Window(object):
    def setupUi(self, Task3Window):
        Task3Window.setObjectName("Task3Window")
        Task3Window.resize(600, 300)
        self.centralwidget = QtWidgets.QWidget(Task3Window)
        self.centralwidget.setObjectName("centralwidget")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.vboxlayout.setObjectName("vboxlayout")
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.le_contact_name = QtWidgets.QLineEdit(self.centralwidget)
        self.le_contact_name.setObjectName("le_contact_name")
        self.hboxlayout.addWidget(self.le_contact_name)
        self.le_contact_phone = QtWidgets.QLineEdit(self.centralwidget)
        self.le_contact_phone.setObjectName("le_contact_phone")
        self.hboxlayout.addWidget(self.le_contact_phone)
        self.btn_add_contact = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add_contact.setObjectName("btn_add_contact")
        self.hboxlayout.addWidget(self.btn_add_contact)
        self.vboxlayout.addLayout(self.hboxlayout)
        self.listContacts = QtWidgets.QListWidget(self.centralwidget)
        self.listContacts.setObjectName("listContacts")
        self.vboxlayout.addWidget(self.listContacts)
        Task3Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Task3Window)
        QtCore.QMetaObject.connectSlotsByName(Task3Window)

    def retranslateUi(self, Task3Window):
        _translate = QtCore.QCoreApplication.translate
        self.le_contact_name.setPlaceholderText(_translate("Task3Window", "Имя контакта"))
        self.le_contact_phone.setPlaceholderText(_translate("Task3Window", "Номер телефона"))
        self.btn_add_contact.setText(_translate("Task3Window", "Добавить"))
