# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task4.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Task4Window(object):
    def setupUi(self, Task4Window):
        Task4Window.setObjectName("Task4Window")
        Task4Window.resize(600, 300)
        self.centralwidget = QtWidgets.QWidget(Task4Window)
        self.centralwidget.setObjectName("centralwidget")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.vboxlayout.setObjectName("vboxlayout")
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.spin_start_n = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_start_n.setProperty("value", 20)
        self.spin_start_n.setObjectName("spin_start_n")
        self.hboxlayout.addWidget(self.spin_start_n)
        self.btn_new_game = QtWidgets.QPushButton(self.centralwidget)
        self.btn_new_game.setObjectName("btn_new_game")
        self.hboxlayout.addWidget(self.btn_new_game)
        self.lbl_nim_status = QtWidgets.QLabel(self.centralwidget)
        self.lbl_nim_status.setObjectName("lbl_nim_status")
        self.hboxlayout.addWidget(self.lbl_nim_status)
        self.vboxlayout.addLayout(self.hboxlayout)
        self.hboxlayout1 = QtWidgets.QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.spin_take = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_take.setMinimum(1)
        self.spin_take.setMaximum(3)
        self.spin_take.setObjectName("spin_take")
        self.hboxlayout1.addWidget(self.spin_take)
        self.btn_take = QtWidgets.QPushButton(self.centralwidget)
        self.btn_take.setObjectName("btn_take")
        self.hboxlayout1.addWidget(self.btn_take)
        self.vboxlayout.addLayout(self.hboxlayout1)
        Task4Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Task4Window)
        QtCore.QMetaObject.connectSlotsByName(Task4Window)

    def retranslateUi(self, Task4Window):
        _translate = QtCore.QCoreApplication.translate
        self.btn_new_game.setText(_translate("Task4Window", "Новая игра"))
        self.lbl_nim_status.setText(_translate("Task4Window", "Старт"))
        self.btn_take.setText(_translate("Task4Window", "Взять"))
