# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task5.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Task5Window(object):
    def setupUi(self, Task5Window):
        Task5Window.setObjectName("Task5Window")
        Task5Window.resize(700, 400)
        self.centralwidget = QtWidgets.QWidget(Task5Window)
        self.centralwidget.setObjectName("centralwidget")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.vboxlayout.setObjectName("vboxlayout")
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.dsb_threshold = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.dsb_threshold.setProperty("value", 50.0)
        self.dsb_threshold.setObjectName("dsb_threshold")
        self.hboxlayout.addWidget(self.dsb_threshold)
        self.btn_check = QtWidgets.QPushButton(self.centralwidget)
        self.btn_check.setObjectName("btn_check")
        self.hboxlayout.addWidget(self.btn_check)
        self.vboxlayout.addLayout(self.hboxlayout)
        self.hboxlayout1 = QtWidgets.QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.textA = QtWidgets.QTextEdit(self.centralwidget)
        self.textA.setObjectName("textA")
        self.hboxlayout1.addWidget(self.textA)
        self.textB = QtWidgets.QTextEdit(self.centralwidget)
        self.textB.setObjectName("textB")
        self.hboxlayout1.addWidget(self.textB)
        self.vboxlayout.addLayout(self.hboxlayout1)
        Task5Window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Task5Window)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        Task5Window.setStatusBar(self.statusbar)

        self.retranslateUi(Task5Window)
        QtCore.QMetaObject.connectSlotsByName(Task5Window)

    def retranslateUi(self, Task5Window):
        _translate = QtCore.QCoreApplication.translate
        self.dsb_threshold.setSuffix(_translate("Task5Window", "%"))
        self.btn_check.setText(_translate("Task5Window", "Проверить"))
