# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Task1Window(object):
    def setupUi(self, Task1Window):
        Task1Window.setObjectName("Task1Window")
        Task1Window.resize(400, 200)
        self.centralwidget = QtWidgets.QWidget(Task1Window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBoxTop = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxTop.setObjectName("groupBoxTop")
        self.hboxlayout = QtWidgets.QHBoxLayout(self.groupBoxTop)
        self.hboxlayout.setObjectName("hboxlayout")
        self.rb_top_red = QtWidgets.QRadioButton(self.groupBoxTop)
        self.rb_top_red.setObjectName("rb_top_red")
        self.hboxlayout.addWidget(self.rb_top_red)
        self.rb_top_white = QtWidgets.QRadioButton(self.groupBoxTop)
        self.rb_top_white.setObjectName("rb_top_white")
        self.hboxlayout.addWidget(self.rb_top_white)
        self.verticalLayout.addWidget(self.groupBoxTop)
        self.groupBoxMiddle = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxMiddle.setObjectName("groupBoxMiddle")
        self.hboxlayout1 = QtWidgets.QHBoxLayout(self.groupBoxMiddle)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.rb_mid_green = QtWidgets.QRadioButton(self.groupBoxMiddle)
        self.rb_mid_green.setObjectName("rb_mid_green")
        self.hboxlayout1.addWidget(self.rb_mid_green)
        self.rb_mid_blue = QtWidgets.QRadioButton(self.groupBoxMiddle)
        self.rb_mid_blue.setObjectName("rb_mid_blue")
        self.hboxlayout1.addWidget(self.rb_mid_blue)
        self.verticalLayout.addWidget(self.groupBoxMiddle)
        self.groupBoxBottom = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxBottom.setObjectName("groupBoxBottom")
        self.hboxlayout2 = QtWidgets.QHBoxLayout(self.groupBoxBottom)
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.rb_bot_red = QtWidgets.QRadioButton(self.groupBoxBottom)
        self.rb_bot_red.setObjectName("rb_bot_red")
        self.hboxlayout2.addWidget(self.rb_bot_red)
        self.rb_bot_white = QtWidgets.QRadioButton(self.groupBoxBottom)
        self.rb_bot_white.setObjectName("rb_bot_white")
        self.hboxlayout2.addWidget(self.rb_bot_white)
        self.verticalLayout.addWidget(self.groupBoxBottom)
        self.btn_draw_flag = QtWidgets.QPushButton(self.centralwidget)
        self.btn_draw_flag.setObjectName("btn_draw_flag")
        self.verticalLayout.addWidget(self.btn_draw_flag)
        self.lbl_flag_result = QtWidgets.QLabel(self.centralwidget)
        self.lbl_flag_result.setText("")
        self.lbl_flag_result.setObjectName("lbl_flag_result")
        self.verticalLayout.addWidget(self.lbl_flag_result)
        Task1Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Task1Window)
        QtCore.QMetaObject.connectSlotsByName(Task1Window)

    def retranslateUi(self, Task1Window):
        _translate = QtCore.QCoreApplication.translate
        self.groupBoxTop.setTitle(_translate("Task1Window", "Верхняя полоса"))
        self.rb_top_red.setText(_translate("Task1Window", "Красный"))
        self.rb_top_white.setText(_translate("Task1Window", "Белый"))
        self.groupBoxMiddle.setTitle(_translate("Task1Window", "Средняя полоса"))
        self.rb_mid_green.setText(_translate("Task1Window", "Зелёный"))
        self.rb_mid_blue.setText(_translate("Task1Window", "Синий"))
        self.groupBoxBottom.setTitle(_translate("Task1Window", "Нижняя полоса"))
        self.rb_bot_red.setText(_translate("Task1Window", "Красный"))
        self.rb_bot_white.setText(_translate("Task1Window", "Белый"))
        self.btn_draw_flag.setText(_translate("Task1Window", "Нарисовать"))
