# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Task2Window(object):
    def setupUi(self, Task2Window):
        Task2Window.setObjectName("Task2Window")
        Task2Window.resize(600, 400)
        self.centralwidget = QtWidgets.QWidget(Task2Window)
        self.centralwidget.setObjectName("centralwidget")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.vboxlayout.setObjectName("vboxlayout")
        self.le_event_name = QtWidgets.QLineEdit(self.centralwidget)
        self.le_event_name.setObjectName("le_event_name")
        self.vboxlayout.addWidget(self.le_event_name)
        self.calendar = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendar.setObjectName("calendar")
        self.vboxlayout.addWidget(self.calendar)
        self.timeEdit = QtWidgets.QTimeEdit(self.centralwidget)
        self.timeEdit.setObjectName("timeEdit")
        self.vboxlayout.addWidget(self.timeEdit)
        self.btn_add_event = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add_event.setObjectName("btn_add_event")
        self.vboxlayout.addWidget(self.btn_add_event)
        self.listEvents = QtWidgets.QListWidget(self.centralwidget)
        self.listEvents.setObjectName("listEvents")
        self.vboxlayout.addWidget(self.listEvents)
        Task2Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Task2Window)
        QtCore.QMetaObject.connectSlotsByName(Task2Window)

    def retranslateUi(self, Task2Window):
        _translate = QtCore.QCoreApplication.translate
        self.le_event_name.setPlaceholderText(_translate("Task2Window", "Название события"))
        self.btn_add_event.setText(_translate("Task2Window", "Добавить"))
